//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyLibraryWeb_M3.LoanRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanItemDTO", Namespace="http://schemas.datacontract.org/2004/07/TinyLibraryWeb_M3.Services")]
    [System.SerializableAttribute()]
    public partial class LoanItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanRef.ILoanService")]
    public interface ILoanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/FeeCalcLibrary", ReplyAction="http://tempuri.org/ILoanService/FeeCalcLibraryResponse")]
        decimal FeeCalcLibrary(int daysLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/FeeCalcLibrary", ReplyAction="http://tempuri.org/ILoanService/FeeCalcLibraryResponse")]
        System.Threading.Tasks.Task<decimal> FeeCalcLibraryAsync(int daysLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/Checkout", ReplyAction="http://tempuri.org/ILoanService/CheckoutResponse")]
        bool Checkout(TinyLibraryWeb_M3.LoanRef.LoanItemDTO[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoanService/Checkout", ReplyAction="http://tempuri.org/ILoanService/CheckoutResponse")]
        System.Threading.Tasks.Task<bool> CheckoutAsync(TinyLibraryWeb_M3.LoanRef.LoanItemDTO[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoanServiceChannel : TinyLibraryWeb_M3.LoanRef.ILoanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanServiceClient : System.ServiceModel.ClientBase<TinyLibraryWeb_M3.LoanRef.ILoanService>, TinyLibraryWeb_M3.LoanRef.ILoanService {
        
        public LoanServiceClient() {
        }
        
        public LoanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal FeeCalcLibrary(int daysLate) {
            return base.Channel.FeeCalcLibrary(daysLate);
        }
        
        public System.Threading.Tasks.Task<decimal> FeeCalcLibraryAsync(int daysLate) {
            return base.Channel.FeeCalcLibraryAsync(daysLate);
        }
        
        public bool Checkout(TinyLibraryWeb_M3.LoanRef.LoanItemDTO[] items) {
            return base.Channel.Checkout(items);
        }
        
        public System.Threading.Tasks.Task<bool> CheckoutAsync(TinyLibraryWeb_M3.LoanRef.LoanItemDTO[] items) {
            return base.Channel.CheckoutAsync(items);
        }
    }
}
